// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZsXkeabfP82mLeko9mKhVucwp5MSWe0',
    appId: '1:40985160494:web:6a624662d1cbaab28c28bf',
    messagingSenderId: '40985160494',
    projectId: 'eduinteractive-b4afc',
    authDomain: 'eduinteractive-b4afc.firebaseapp.com',
    storageBucket: 'eduinteractive-b4afc.firebasestorage.app',
    measurementId: 'G-0QFM1BWSGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALe_gGTUaHLMTSpCpeXOkt9tfEGkLtOho',
    appId: '1:40985160494:android:376714e69a626b898c28bf',
    messagingSenderId: '40985160494',
    projectId: 'eduinteractive-b4afc',
    storageBucket: 'eduinteractive-b4afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUozVglkET8fKfvX1z4ZtS7PbALQzbYkM',
    appId: '1:40985160494:ios:76b7ba15db8225bb8c28bf',
    messagingSenderId: '40985160494',
    projectId: 'eduinteractive-b4afc',
    storageBucket: 'eduinteractive-b4afc.firebasestorage.app',
    iosBundleId: 'com.eduinteractive.eduInteractive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUozVglkET8fKfvX1z4ZtS7PbALQzbYkM',
    appId: '1:40985160494:ios:76b7ba15db8225bb8c28bf',
    messagingSenderId: '40985160494',
    projectId: 'eduinteractive-b4afc',
    storageBucket: 'eduinteractive-b4afc.firebasestorage.app',
    iosBundleId: 'com.eduinteractive.eduInteractive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZsXkeabfP82mLeko9mKhVucwp5MSWe0',
    appId: '1:40985160494:web:a71938feddee9f298c28bf',
    messagingSenderId: '40985160494',
    projectId: 'eduinteractive-b4afc',
    authDomain: 'eduinteractive-b4afc.firebaseapp.com',
    storageBucket: 'eduinteractive-b4afc.firebasestorage.app',
    measurementId: 'G-MBH8Z25PYX',
  );
}
